services:
  python-ai:
    build:
      context: ./python-ai
    container_name: python-ai
    env_file:
      - ./python-ai/.env
    ports:
      - "8001:8001"
    environment:
      - ENV=production
    restart: unless-stopped

  go-backend:
    build:
      context: .
      dockerfile: go-backend/Dockerfile
    container_name: go-backend
    env_file:
      - ./go-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - python-ai
    environment:
      - PYTHON_AI_URL=http://python-ai:8001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - go-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
